Tests on Linux indicates that matrixStats 0.15.0 requires R (>= 2.12.0)
For instance with R version 2.11.1 (2010-05-31) on
x86_64-unknown-linux-gnu, we get:
```
* installing *source* package 'matrixStats' ...
** libs
gcc -std=gnu99
-I/home/shared/cbc/software_cbc/R/R-2.11.1-20150918/lib64/R/include
-I/home/shared/cbc/local/include     -fpic  -Wl,-rpath=/opt/tools/lib
-Wl,-rpath=/opt/NetCDF/NetCDF-4.3.0/lib
-Wl,-rpath=/opt/gcc/gcc-4.9.2/lib64 -c allocMatrix2.c -o allocMatrix2.o
In file included from allocMatrix2.c:2:0:
allocMatrix2.c: In function 'allocArray2':
types.h:8:20: error: 'INT_MAX' undeclared (first use in this function)
 #define R_INT_MAX  INT_MAX
         ^
allocMatrix2.c:164:14: note: in expansion of macro 'R_INT_MAX'
     if (nd > R_INT_MAX) {
              ^
types.h:8:20: note: each undeclared identifier is reported only once for each function it appears in
     #define R_INT_MAX  INT_MAX
                        ^
allocMatrix2.c:164:14: note: in expansion of macro 'R_INT_MAX'
     if (nd > R_INT_MAX) {
              ^
make: *** [allocMatrix2.o] Error 1
ERROR: compilation failed for package 'matrixStats'
```